version: '3'

services:
    cassandra-gui:
        build: .
        container_name: cassandra-gui
        ports:
            - 9114:3000
        command: cassandra-web --hosts '209.97.164.196' --port '9042'