version: '3'

services:
    cassandra-gui:
        build: .
        container_name: cassandra-gui
        ports:
            - 9114:3000
        command: cassandra-web --hosts '127.0.0.1' --port '9042'